### ISSUE TITLE
[FEAT] : 기본 구조 및 구성화면 구현

### ISSUE THREAD

**Issue by wjdrjs00** [COINKIRI/coinkiri-AOS#3]
## Description 📝
프로젝트 앱 기본 구조 및 구성화면 구현(분석,커뮤니티,홈,시세,내정보)

## To-Do ☑️
- [x] 프로젝트 기본 구조 구성
- [x] 메인 바텀바, 바텀네비게이션 구현
- [x] 각 화면 추가

**Comment by yeong0jae** [comment]
good 이네요
